version: "3.8"

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=silicorn
    ports:
      - "3316:3306"
    volumes:
      - ./data:/var/lib/mysql
