"""ceo_id removed from unprocessed companies

Revision ID: d67ad5f20671
Revises: 937b56f5d3d4
Create Date: 2024-01-12 17:29:13.195766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd67ad5f20671'
down_revision: Union[str, None] = '937b56f5d3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unprocessed_companies', 'ceo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unprocessed_companies', sa.Column('ceo_id', mysql.VARCHAR(length=12), nullable=True))
    # ### end Alembic commands ###
